# Retrieve all facilities of a particular set of industries (for example, all power generation facilities as indicated by the four-digit NAICS code 2211) and the county they are located in (Administrative Regions Level 2) for facilities in a specific administrative region (e.g. the state of Illinois, FIPS code 17).
 
PREFIX kwgr: <http://stko-kwg.geog.ucsb.edu/lod/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epa-frs: <http://w3id.org/fio/v1/epa-frs#>
PREFIX fio: <http://w3id.org/fio/v1/fio#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX naics: <http://w3id.org/fio/v1/naics#>
PREFIX kwg-ont: <http://stko-kwg.geog.ucsb.edu/lod/ontology/>
select * where {
        ?facility rdf:type epa-frs:EPA-PFAS-Facility ;
    		fio:ofIndustry ?code .
        	?code 	fio:subcodeOf ?icode ;
    				rdfs:label ?code_label .
    	FILTER (?icode IN (naics:NAICS-2211))
		?facility kwg-ont:sfWithin | kwg-ont:sfOverlaps  ?region .
    SERVICE <repository:Spatial> {
		?region rdf:type kwg-ont:AdministrativeRegion_3 .
		?region kwg-ont:administrativePartOf ?county.
        ?county kwg-ont:administrativePartOf kwgr:administrativeRegion.USA.17;
        		rdf:type kwg-ont:AdministrativeRegion_2;
				rdfs:label ?countyName. 
	}
	}